<html><head><title>MATRIX</title></head><body BGCOLOR=""><BODY TEXT="#000066"><center><table border=0 align=center><tr><td align=center bgcolor="#cccccc"><A NAME="Arriba"><font size=5>CIRUGIAS CANCELADAS</font></a></td></tr><tr><td align=center bgcolor="#cccccc"><font size=2> <b> Canceladas.php</b></font></td></tr></table></center><?php
include_once("conex.php"); session_start(); if(!isset($_SESSION['user'])) echo "error"; else { $key = substr($user,2,strlen($user));

echo "<form action='Canceladas.php' method=post>";if(!isset($v0) or !isset($v1)){ echo  "<center><table border=0>"; echo "<tr><td align=center colspan=2><b>PROMOTORA MEDICA LAS AMERICAS S.A.<b></td></tr>"; echo "<tr><td colspan=2 align=center><b>CIRUGIAS CANCELADAS</b></td></tr>"; echo  "<tr><td bgcolor=#cccccc align=center>Documento</td>"; echo  "<td bgcolor=#cccccc align=center><input type='TEXT' name='v0' size=12 maxlength=12></td></tr>"; echo  "<tr><td bgcolor=#cccccc align=center>Paciente</td>"; echo  "<td bgcolor=#cccccc align=center><input type='TEXT' name='v1' size=40 maxlength=40></td></tr>";echo "<tr><td bgcolor=#cccccc  colspan=2 align=center><input type='submit' value='ENTER'></td></tr></table>";}else{$query = "select Mcatur,Mcaqui,Mcahin,Mcahfi,Mcafec,Mcadoc,Mcahis,Mcanom,Mcafna,Mcasex,Mcaeps,Entdes,Mcacir,Mcamed,Mcaequ,Mcacau,Candes from tcx_000007,tcx_000003,tcx_000001 ";
$query .= " where mcadoc like '%".$v0."%' ";
$query .= "   and mcanom like '%".$v1."%' ";
$query .= "   and mcaeps = entcod ";
$query .= "   and mcacau = cancod ";
$query .= "  order by 5,2,3 ";
$err = mysql_query($query,$conex);$num = mysql_num_rows($err); echo "<table border=1>"; echo "<tr><td colspan=17 align=center><b>PROMOTORA MEDICA LAS AMERICAS S.A.</b></td></tr>"; echo "<tr><td colspan=17 align=center><b>DIRECCION DE INFORMATICA</b></td></tr>"; echo "<tr><td colspan=17 align=center><b>CIRUGIAS CANCELADAS</b></td></tr>"; echo "<tr>"; echo "<td bgcolor=#cccccc><b>Turno</b></td>"; echo "<td bgcolor=#cccccc><b>Quirofano</b></td>"; echo "<td bgcolor=#cccccc><b>Hora<BR>Inicio</b></td>"; echo "<td bgcolor=#cccccc><b>Hora<BR>Final</b></td>"; echo "<td bgcolor=#cccccc><b>Fecha</b></td>"; echo "<td bgcolor=#cccccc><b>Documento</b></td>"; echo "<td bgcolor=#cccccc><b>Historia</b></td>"; echo "<td bgcolor=#cccccc><b>Paciente</b></td>"; echo "<td bgcolor=#cccccc><b>Fecha<br>Nacimiento</b></td>"; echo "<td bgcolor=#cccccc><b>Sexo</b></td>"; echo "<td bgcolor=#cccccc><b>Nit<br>Eps</b></td>"; echo "<td bgcolor=#cccccc><b>Nonbre<br>Eps</b></td>"; echo "<td bgcolor=#cccccc><b>Cirugias</b></td>"; echo "<td bgcolor=#cccccc><b>Medicos</b></td>"; echo "<td bgcolor=#cccccc><b>Equipos</b></td>"; echo "<td bgcolor=#cccccc><b>Codigo<br>Cancel.</b></td>"; echo "<td bgcolor=#cccccc><b>Descrip.<br>Cancel.</b></td>"; echo "</tr>"; $t=array();$t[0] = 0;$t[1] = 0;$t[2] = 0;$t[3] = 0;$t[4] = 0;$t[5] = 0;$t[6] = 0;$t[7] = 0;$t[8] = 0;$t[9] = 0;$t[10] = 0;$t[11] = 0;$t[12] = 0;$t[13] = 0;$t[14] = 0;$t[15] = 0;$t[16] = 0;for ($i=0;$i<$num;$i++){$row = mysql_fetch_array($err); echo "<tr>"; echo "<td>".$row[0]."</td>"; echo "<td>".$row[1]."</td>"; echo "<td>".$row[2]."</td>"; echo "<td>".$row[3]."</td>"; echo "<td>".$row[4]."</td>"; echo "<td>".$row[5]."</td>"; echo "<td>".$row[6]."</td>"; echo "<td>".$row[7]."</td>"; echo "<td>".$row[8]."</td>"; echo "<td>".$row[9]."</td>"; echo "<td>".$row[10]."</td>"; echo "<td>".$row[11]."</td>"; echo "<td>".$row[12]."</td>"; echo "<td>".$row[13]."</td>"; echo "<td>".$row[14]."</td>"; echo "<td>".$row[15]."</td>"; echo "<td>".$row[16]."</td>"; echo "</tr>"; } echo "</table>"; }}?></body></html>